[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 10.25
[keyboard]
bindings = [
  { key = "Slash", mods = "Control", chars = "\u001f" },
  { key = "Space", mods = "Control", chars = "\u0000" },
]
[terminal]
shell = { program = "pwsh", args = ["-NoLogo"] }
