local dap = require("dap")
local inspect = require("vim.inspect")

local b = vim.opt.background
print(vim.inspect(b))
print(b:get())
local function dap_color(h, c)
  vim.api.nvim_set_hl(0, "DapUIScope", { link = "@lsp.type.variable" })
  vim.api.nvim_set_hl(0, "DapUIStepOver", { link = "@lsp.type.variable" })
  vim.api.nvim_set_hl(0, "DapUIStepOverNC", { link = "@lsp.type.variable" })
  vim.api.nvim_set_hl(0, "DapUIStepInto", { link = "@lsp.type.variable" })
  vim.api.nvim_set_hl(0, "DapUIStepIntoNC", { link = "@lsp.type.variable" })
  vim.api.nvim_set_hl(0, "DapUIStepOut", { link = "@lsp.type.variable" })
  vim.api.nvim_set_hl(0, "DapUIStepOutNC", { link = "@lsp.type.variable" })
  vim.api.nvim_set_hl(0, "DapUIStepBack", { link = "@lsp.type.variable" })
  vim.api.nvim_set_hl(0, "DapUIStepBackNC", { link = "@lsp.type.variable" })
  vim.api.nvim_set_hl(0, "DapUILineNumber", { link = "@lsp.type.variable" })
  vim.api.nvim_set_hl(0, "DapUIDecoration", { link = "@lsp.type.variable" })
  vim.api.nvim_set_hl(0, "DapUIBreakpointsPath", { link = "@lsp.type.variable" })
  vim.api.nvim_set_hl(0, "DapUIBreakpointsLine", { link = "@lsp.type.variable" })
  vim.api.nvim_set_hl(0, "DapUIStoppedThread", { link = "@lsp.type.variable" })
  --
  vim.api.nvim_set_hl(0, "DapUIRestart", { link = "@attribute" })
  vim.api.nvim_set_hl(0, "DapUIRestartNC", { link = "@attribute" })
  vim.api.nvim_set_hl(0, "DapUIPlayPause", { link = "@attribute" })
  vim.api.nvim_set_hl(0, "DapUIPlayPauseNC", { link = "@attribute" })
  vim.api.nvim_set_hl(0, "DapUIThread", { link = "@attribute" })
  vim.api.nvim_set_hl(0, "DapUIBreakpointsInfo", { link = "@attribute" })
  vim.api.nvim_set_hl(0, "DapUIWatchesValue", { link = "@attribute" })
end
