accelerate:
	docker build -t accelerate -f accelerate.dockerfile .

deeplearning_general:
	docker build -t deeplearning_general -f deeplearning_general.dockerfile .

slr:
	docker build -t slr -f slr.dockerfile .

slt_rocm:
	docker build -t slt_rocm -f slt_rocm.dockerfile .

llamafactory:
	docker build -t llamafactory -f llama_factory.dockerfile .

axolotl:
	docker build -t axolotl -f axotolt.dockerfile .

transformers:
	docker build -t transformers -f transformers.dockerfile .
