accelerate:
	docker build -t accelerate -f accelerate.dockerfile .

deeplearning_general:
	docker build -t deeplearning_general -f deeplearning_general.dockerfile .

slr:
	docker build -t slr -f slr.dockerfile .

slt_rocm:
	docker build -t slt_rocm -f slt_rocm.dockerfile .

