local submode = require("submode")
-- debug submode
vim.keymap.set("n", "<leader>!", function()
  submode.enter("Debug")
end, { desc = "Enter debug mode" })
submode.create("Debug", {
  mode = "n",
  enter = nil,
  leave = { "<leader>!" },
  default = function(register)
    -- scope
    register("<localleader>s", function()
      local w = require("dap.ui.widgets")
      -- w.sidebar(w.sessions, {}, "5 sp | setl winfixheight").toggle()
      w.centered_float(w.scopes)
    end, { desc = "Dap Scopes" })
    -- scope
    register("<localleader>.", function()
      local w = require("dap.ui.widgets")
      -- w.sidebar(w.sessions, {}, "5 sp | setl winfixheight").toggle()
      w.centered_float(w.sessions, {})
    end, { desc = "Dap sessions" })
    register("<localleader>t", function()
      require("dap").terminate()
    end, { desc = "Toggle Breakpoint" })
    register("<localleader>r", function()
      require("dap").restart()
    end, { desc = "Restart" })
    register("<localleader>c", function()
      require("dap").continue()
    end, { desc = "Continue" })
    register("<localleader><localleader>", function()
      require("dap").step_over()
    end, { desc = "Step Over" })
    register("<localleader>o", function()
      require("dap").step_over()
    end, { desc = "Step Over" })
    register("<localleader>e", function()
      require("dap.ui.widgets").hover(nil, { border = "single" })
    end, { desc = "Evaluate" })
    -- register("<C-q>", nil, {  desc = "exit" })
    register("<localleader>a", function()
      require("dap-view").add_expr()
    end, { desc = "add expression" })
    register("<localleader>W", function()
      require("dap-view").jump_to_view("watches")
    end, { desc = "Jump to Watches" })
    register("<localleader>S", function()
      require("dap-view").jump_to_view("scopes")
    end, { desc = "Jump to Scopes" })
    register("<localleader>T", function()
      require("dap-view").jump_to_view("threads")
    end, { desc = "Jump to Threads" })
    register("<localleader>R", function()
      require("dap-view").jump_to_view("repl")
    end, { desc = "Jump to Repl" })
    register("<localleader>B", function()
      require("dap-view").jump_to_view("breakpoints")
    end, { desc = "Jump to Breakpoints" })
    register("<localleader>E", function()
      require("dap-view").jump_to_view("exceptions")
    end, { desc = "Jump to Expressions" })
  end,
})
