-- set up python dap it was set by nvim-dap-python
local dap = require("dap")

-- dap.adapters.mypy = function(cb, config)
--   cb({
--     type = "executable",
--     command = "debugpy",
--     args = { "-m", "debugpy.adapter" },
--   })
-- end
--
-- local configs = dap.configurations.python
-- table.insert(configs, {
--   type = "mypy",
--   request = "launch",
--   name = "Launch mmmmmmmm file",
--   program = "${file}",
--   pythonPath = function()
--     return vim.fn.exepath("python")
--   end,
-- })
